Repository openshift-pipelines/console-plugin, pull requests merged in 2023-12, with the labels that each got.

#17 ODC-7411: Update i18n and move some parts of readme to contributing
  CONTRIBUTING.md
  README.md
  locales/en/console-shared.json
  locales/en/plugin__pipeline-console-plugin.json
  locales/en/public.json
  src/components/pipelines-overview/PipelineRunsStatusCard.tsx
  src/models.ts
Labels: approved, lgtm, jira/valid-reference

#21 ODC-7440: API integration in PipelineRun status card
  locales/en/plugin__pipeline-console-plugin.json
  src/components/Loading.tsx
  src/components/pipelines-metrics/PipelinesMetricsPage.tsx
  src/components/pipelines-overview/PipelineRunsStatusCard.tsx
  src/components/pipelines-overview/PipelinesOverview.scss
  src/components/pipelines-overview/PipelinesOverviewPage.tsx
  src/components/pipelines-overview/utils.ts
  src/components/utils/tekton-results.ts
Labels: approved, lgtm, jira/valid-reference

#23 ODC-7440: fix for all namespace selection
  src/components/pipelines-overview/PipelineRunsStatusCard.tsx
Labels: approved, lgtm, jira/valid-reference

#25 ODC-7455: consmetic changes in Charts and number cards
  src/components/pipelines-metrics/PipelinesAverageDuration.tsx
  src/components/pipelines-overview/PipelineRunsDurationCard.scss
  src/components/pipelines-overview/PipelineRunsDurationCard.tsx
  src/components/pipelines-overview/PipelineRunsNumbersChart.tsx
  src/components/pipelines-overview/PipelineRunsStatusCard.tsx
  src/components/pipelines-overview/PipelineRunsTotalCard.scss
  src/components/pipelines-overview/PipelineRunsTotalCard.tsx
Labels: approved, lgtm, jira/valid-reference

#26 Added Interval for Duration,TotalRuns,NoOfPipelineRuns & Status
  src/components/pipelines-metrics/PipelinesMetricsPage.tsx
  src/components/pipelines-overview/PipelineRunsDurationCard.tsx
  src/components/pipelines-overview/PipelineRunsNumbersChart.tsx
  src/components/pipelines-overview/PipelineRunsStatusCard.tsx
  src/components/pipelines-overview/PipelineRunsTotalCard.tsx
  src/components/pipelines-overview/PipelinesOverviewPage.tsx
  src/components/pipelines-overview/utils.ts
Labels: approved, lgtm

#24 ODC-7442: Integrate the tektonResults API in the PipelineRuns list
  src/components/pipelines-metrics/PipelinesMetricsPage.tsx
  src/components/pipelines-overview/PipelineRunsStatusCard.tsx
  src/components/pipelines-overview/PipelinesOverviewPage.tsx
  src/components/pipelines-overview/SearchInput.tsx
  src/components/pipelines-overview/dateTime.ts
  src/components/pipelines-overview/list-pages/PipelineRunsForPipelinesList.tsx
  src/components/pipelines-overview/list-pages/PipelineRunsForPipelinesRow.tsx
  src/components/pipelines-overview/list-pages/PipelineRunsForRepositoriesList.tsx
  src/components/pipelines-overview/list-pages/PipelineRunsForRepositoriesRow.tsx
  src/components/pipelines-overview/list-pages/PipelineRunsListPage.tsx
  src/components/pipelines-overview/utils.ts
  src/components/utils/tekton-results.ts
Labels: approved, lgtm, jira/valid-reference

#27 Change per Pipeline and per Repository toggle button order
  locales/en/plugin__pipeline-console-plugin.json
  src/components/pipelines-overview/list-pages/PipelineRunsListPage.tsx
Labels: approved, lgtm

#29 ODC-7458: Added inline loading for all components
  src/components/pipelines-overview/PipelineRunsDurationCard.tsx
  src/components/pipelines-overview/PipelineRunsNumbersChart.tsx
  src/components/pipelines-overview/PipelineRunsStatusCard.tsx
  src/components/pipelines-overview/PipelineRunsTotalCard.tsx
  src/components/pipelines-overview/list-pages/PipelineRunsForPipelinesList.tsx
  src/components/pipelines-overview/list-pages/PipelineRunsForRepositoriesList.tsx
  src/components/pipelines-overview/list-pages/PipelineRunsListPage.tsx
Labels: approved, lgtm, jira/valid-reference

#30 OCPBUGS-25334: shows correct data on BarCharts
  src/components/pipelines-overview/PipelineRunsNumbersChart.tsx
  src/components/pipelines-overview/PipelineRunsStatusCard.tsx
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#31 fix: chart tick style padding fix
  src/components/pipelines-metrics/PipelinesAverageDuration.tsx
  src/components/pipelines-overview/PipelineRunsNumbersChart.tsx
  src/components/pipelines-overview/PipelineRunsStatusCard.tsx
Labels: approved, lgtm

#28 ODC-7443: Integrate metrics tab for Pipeline and Repository with Summary API
  console-extensions.json
  locales/en/plugin__pipeline-console-plugin.json
  src/components/pipelines-metrics/PipelinesAverageDuration.tsx
  src/components/pipelines-metrics/PipelinesMetrics.scss
  src/components/pipelines-metrics/PipelinesMetricsPage.tsx
  src/components/pipelines-overview/PipelineRunsDurationCard.tsx
  src/components/pipelines-overview/PipelineRunsNumbersChart.tsx
  src/components/pipelines-overview/PipelineRunsStatusCard.tsx
  src/components/pipelines-overview/PipelinesOverviewPage.tsx
  src/components/pipelines-overview/dateTime.ts
  src/components/pipelines-overview/utils.ts
Labels: approved, lgtm, jira/valid-reference

#34 fix: status chart fix for NaN and Popover
  src/components/pipelines-metrics/PipelinesAverageDuration.tsx
  src/components/pipelines-overview/PipelineRunsNumbersChart.tsx
  src/components/pipelines-overview/PipelineRunsStatusCard.tsx
Labels: approved, lgtm

#35 ODC-7462: Hide standalone PipelineRuns by req. spec.pipelineRef.name for Pipeline PLRs
  src/components/pipelines-overview/PipelineRunsTotalCard.tsx
  src/components/pipelines-overview/list-pages/PipelineRunsListPage.tsx
  src/components/pipelines-overview/utils.ts
Labels: approved, lgtm, jira/valid-reference

#37 fix: Added link to total runs in list page to redirect to plr tab
  src/components/pipelines-overview/list-pages/PipelineRunsForPipelinesRow.tsx
  src/components/pipelines-overview/list-pages/PipelineRunsForRepositoriesRow.tsx
Labels: approved, lgtm

#39 fix: Updated namespace link name
  src/components/pipelines-overview/list-pages/PipelineRunsForPipelinesRow.tsx
  src/components/pipelines-overview/list-pages/PipelineRunsForRepositoriesRow.tsx
Labels: approved, lgtm

#36 Add small scripts to connect to the postgres and show the api-log
  .gitignore
  scripts/api-log.sh
  scripts/psql-cluster.sh
Labels: approved, lgtm

#38 Create a TypeScript script to create some demo data
  scripts/db-create-demo-data.sh
  scripts/db-show-stats.sh
  scripts/db/create-demo-data.ts
  scripts/db/package.json
  scripts/db/show-stats.ts
  scripts/db/tsconfig.json
  scripts/db/utils/date-utils.ts
  scripts/db/utils/history-utils.ts
  scripts/db/yamls/PipelineRun-failed.yaml
  scripts/db/yamls/PipelineRun-succeeded.yaml
  scripts/db/yarn.lock
  scripts/psql-port-forward.sh
Labels: approved, lgtm

#42 ODC-7472: Update last run time to support unix timestamp
  src/components/pipelines-overview/dateTime.ts
  src/components/pipelines-overview/list-pages/PipelineRunsForPipelinesList.tsx
  src/components/pipelines-overview/list-pages/PipelineRunsForRepositoriesList.tsx
  src/components/pipelines-overview/utils.ts
Labels: approved, lgtm, jira/valid-reference

#41 ODC-7471: Configure prettier and fix prettier error
  .ci-operator.yaml
  .devcontainer/devcontainer.json
  .editorconfig
  .eslintignore
  .prettierignore
  .stylelintrc.yaml
  .vscode/settings.json
  CONTRIBUTING.md
  README.md
  charts/openshift-console-plugin/templates/configmap.yaml
  charts/openshift-console-plugin/templates/consoleplugin.yaml
  charts/openshift-console-plugin/values.yaml
  i18n-scripts/lexers.js
  integration-tests/.eslintrc
  integration-tests/reporter-config.json
  integration-tests/tsconfig.json
  locales/en/plugin__pipeline-console-plugin.json
  openapi/spec.yml
  scripts/db/tsconfig.json
  src/components/example.css
  src/components/pipelines-metrics/PipelinesAverageDuration.tsx
  src/components/pipelines-overview/PipelineRunsDurationCard.scss
  src/components/pipelines-overview/PipelineRunsDurationCard.tsx
  src/components/pipelines-overview/PipelineRunsTotalCard.scss
  src/components/pipelines-overview/PipelineRunsTotalCard.tsx
  src/components/pipelines-overview/SearchInput.tsx
  src/components/pipelines-overview/list-pages/PipelineRunsForPipelinesList.tsx
  src/components/pipelines-overview/list-pages/PipelineRunsForPipelinesRow.tsx
  src/components/pipelines-overview/list-pages/PipelineRunsForRepositoriesList.tsx
  src/components/pipelines-overview/list-pages/PipelineRunsForRepositoriesRow.tsx
  src/components/pipelines-overview/list-pages/PipelineRunsListPage.tsx
  webpack.config.ts
Labels: approved, lgtm, jira/valid-reference

#43 fix: For 1st plr show - for last runtime until it is completed
  src/components/pipelines-overview/dateTime.ts
Labels: approved, lgtm
