Repository openshift-pipelines/console-plugin, pull requests merged in 2024-07, with the labels that each got.

#126 SRVKP-5769: Fix Edit Pipeline option link on Pipeline details page
  src/components/pipelines-details/PipelineDetailsPage.tsx
Labels: approved, lgtm, jira/valid-reference

#117 ODC-7591: Add unit tests
  babel.config.js
  jest.config.ts
  package.json
  src/components/Loading.tsx
  src/components/auto-complete/__tests__/autoCompleteUtils.spec.ts
  src/components/common/button-bar.jsx
  src/components/common/dropdown.jsx
  src/components/details-page/details-item.tsx
  src/components/details-page/label-list.tsx
  src/components/hooks/__tests__/hooks.spec.ts
  src/components/hooks/__tests__/usePipelineFromPipelineRun.spec.ts
  src/components/hooks/__tests__/usePipelineRunVulnerabilities.spec.ts
  src/components/logs/__tests__/log-snippet-test-data.ts
  src/components/logs/__tests__/log-snippet-utils.spec.ts
  src/components/logs/__tests__/logs-test-data.ts
  src/components/logs/__tests__/logs-utils.spec.ts
  src/components/modals/modal.tsx
  src/components/pipeline-topology/ApprovalTaskNode.tsx
  src/components/pipeline-topology/PipelineTopologyGraph.tsx
  src/components/pipeline-topology/TaskList.tsx
  src/components/pipeline-topology/WhenExpressionDecorator.tsx
  src/components/pipeline-topology/__tests__/WhenExpressionDecorator.spec.tsx
  src/components/pipeline-topology/__tests__/dag.spec.ts
  src/components/pipeline-topology/__tests__/utils.spec.ts
  src/components/pipelines-details/PipelineVisualization.tsx
  src/components/pipelines-details/StatusIcon.tsx
  src/components/pipelines-details/__tests__/PipelineVisualization.spec.tsx
  src/components/pipelines-details/__tests__/pipeline-form-validation-utils.spec.ts
  src/components/pipelines-details/multi-column-field/FormFooter.tsx
  src/components/pipelines-metrics/PipelinesAverageDuration.tsx
  src/components/pipelines-overview/PipelineRunsDurationCard.tsx
  src/components/pipelines-overview/PipelineRunsNumbersChart.tsx
  src/components/pipelines-overview/PipelineRunsStatusCard.tsx
  src/components/pipelines-overview/PipelineRunsTotalCard.tsx
  src/components/pipelines-overview/list-pages/PipelineRunsListPage.tsx
  src/components/pipelines-tasks/tasks-details-pages/__tests__/taskRunLogSnippet.spec.ts
  src/components/pipelines-tasks/tasks-details-pages/events/__tests__/event-utils.spec.ts
  src/components/pipelines-tasks/tasks-details-pages/events/events.jsx
  src/components/pipelines-tasks/tasks-details-pages/events/toggle-play.jsx
  src/components/pipelines-tasks/tasks-details-pages/headings.tsx
  src/components/start-pipeline/__tests__/validation-utils.spec.ts
  src/components/status/status-box.tsx
  src/components/triggers-details/DynamicResourceLinkList.tsx
  src/components/triggers-details/PipelineResourceRef.tsx
  src/components/utils/__tests__/pipeline-augment-test-data.ts
  src/components/utils/__tests__/pipeline-augment.spec.ts
  src/components/utils/__tests__/pipeline-filter-reducer.spec.ts
  src/components/utils/__tests__/pipeline-serviceaccount-test-data.ts
  src/components/utils/__tests__/pipeline-test-data.ts
  src/components/utils/__tests__/pipeline-utils.spec.ts
  src/components/utils/__tests__/render-utils.spec.tsx
  src/test-data/event-listener-data.ts
  src/test-data/pipeline-data.ts
  src/test-data/task-data.ts
  src/test-data/taskrun-test-data.ts
  src/test-data/utils/hooks-utils.tsx
  src/types/coreTekton.ts
  src/types/pipeline.ts
  src/types/pipelineRun.ts
  yarn.lock
Labels: approved, lgtm, jira/valid-reference

#128 OCPBUGS-36260: Tooltip on Pipeline when expression is not shows
  src/components/pipeline-topology/PipelineTaskNode.tsx
  src/components/pipeline-topology/utils.ts
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#129 OCPBUGS-33521: Update sorting in pipeline, pipelineRun and TaskRun list pages
  package.json
  src/components/pipelineRuns-list/PipelineRunsList.tsx
  src/components/pipelines-list/PipelinesList.tsx
  src/components/pipelines-tasks/TaskRunsList.tsx
  yarn.lock
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#132 SRVKP-5784: Add timestamps in the PipelineRuns logs
  src/components/logs/Logs.tsx
  src/components/logs/logs-utils.ts
Labels: approved, lgtm, jira/valid-reference

#135 OCPBUGS-35301: add missing translation in TriggerBindingSection
  locales/en/plugin__pipelines-console-plugin.json
  src/components/start-pipeline/form-sections/TriggerBindingSection.tsx
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug, jira/severity-low

#138 SRVKP-5836: In metrics overview page of tekton results, Average duration chart y-axis is always set to 5m
  src/components/pipelines-metrics/PipelinesAverageDuration.tsx
Labels: approved, lgtm, jira/valid-reference

#140 NO-JIRA: update readme: replace wip note with a feature list
  README.md
Labels: approved, lgtm, jira/valid-reference

#131 SRVKP-5880: Switch to use annotations as labels from PipelineRuns created through Pipelines as Code is deprecated
  src/components/pipelineRuns-details/RepositoryLinkList.tsx
  src/components/pipelineRuns-list/PipelineRunsRow.tsx
  src/components/pipelineRuns-list/usePipelineRunsColumns.ts
  src/components/repositories-list/RepositoriesRow.tsx
  src/components/utils/repository-utils.tsx
  src/consts.ts
  src/test-data/pipeline-data.ts
Labels: approved, lgtm, jira/valid-reference

#143 SRVKP-5881: Fix StorageClass dropdown to show in volumeClaimTemplate form
  src/components/common/StorageClassDropdown.tsx
Labels: approved, lgtm, jira/valid-reference

#141 ODC-7598: Added e2e tests for data source filter group
  integration-tests/cypress/features/pipelines/data-source-filter.feature
  integration-tests/cypress/support/step-definitions/pipelines/data-source-filter.ts
  integration-tests/cypress/testData/pipeline-with-pipelinerun-tasrun.yaml
Labels: approved, lgtm, jira/valid-reference

#145 [release-v1.15.x] SRVKP-5880: Switch to use annotations as labels from PipelineRuns created through Pipelines as Code is deprecated
  src/components/pipelineRuns-details/RepositoryLinkList.tsx
  src/components/pipelineRuns-list/PipelineRunsRow.tsx
  src/components/pipelineRuns-list/usePipelineRunsColumns.ts
  src/components/repositories-list/RepositoriesRow.tsx
  src/components/utils/repository-utils.tsx
  src/consts.ts
Labels: approved, lgtm, jira/valid-reference
