Repository openshift-pipelines/console-plugin, pull requests merged in 2024-01, with the labels that each got.

#15 ODC-7416: Add react testing library for unit tests
  .gitignore
  __mocks__/dummy.ts
  __mocks__/react-i18next.ts
  __mocks__/serverFlags.js
  jest.config.ts
  package.json
  src/components/pipelines-overview/PipelineRunsDurationCard.tsx
  src/components/pipelines-overview/PipelineRunsNumbersChart.tsx
  src/components/pipelines-overview/PipelineRunsStatusCard.tsx
  src/components/pipelines-overview/PipelineRunsTotalCard.tsx
  src/components/pipelines-overview/__tests__/PipelinesOverview.spec.tsx
  src/components/pipelines-overview/list-pages/PipelineRunsListPage.tsx
  tsconfig.json
  yarn.lock
Labels: approved, lgtm, jira/valid-reference

#40 ODC-7469: Use line chart for PipelineRun status
  src/components/pipelines-overview/PipelineRunsStatusCard.tsx
Labels: approved, lgtm, jira/valid-reference

#44 ODC-7466: Fix design issue as per the UX design
  src/components/pipelines-metrics/PipelinesAverageDuration.tsx
  src/components/pipelines-overview/PipelineRunsNumbersChart.tsx
  src/components/pipelines-overview/PipelineRunsStatusCard.tsx
  src/components/pipelines-overview/PipelinesOverview.scss
  src/components/pipelines-overview/dateTime.ts
Labels: approved, lgtm, jira/valid-reference

#45 OCPBUGS-26531: Fix cache issue for dev env
  webpack.config.ts
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#20 ODC-7417: Add scripts for Development setup
  scripts/install-operator-results-api.sh
Labels: approved, lgtm, jira/valid-reference

#47 ODC-7482: Add flags to hide static plugin List and details pages
  src/components/hooks/flagHookProvider.ts
  src/consts.ts
Labels: approved, lgtm, jira/valid-reference

#50 Fix chart yaml files format
  .prettierignore
  charts/openshift-console-plugin/templates/configmap.yaml
  charts/openshift-console-plugin/templates/consoleplugin.yaml
  charts/openshift-console-plugin/templates/deployment.yaml
Labels: approved, lgtm

#51 update test scripts to run e2e and unit tests
  test-frontend.sh
  test-prow-e2e.sh
Labels: approved, lgtm

#52 fix unit tests
  src/components/pipelines-overview/PipelineRunsNumbersChart.tsx
  src/components/pipelines-overview/PipelineRunsStatusCard.tsx
Labels: approved, lgtm

#53 update plugin__pipeline-console-plugin.json
  locales/en/plugin__pipeline-console-plugin.json
Labels: approved

#54 Fix (hopefully some) issues with updated CI config
  i18n-scripts/build-i18n.sh
  package.json
  src/components/pipelines-overview/PipelineRunsStatusCard.tsx
  src/components/pipelines-overview/utils.ts
  test-frontend.sh
  test-prow-e2e.sh
  yarn.lock
Labels: approved, lgtm

#48 ODC-7470: Make Time Range Dropdown options dynamic
  locales/en/plugin__pipeline-console-plugin.json
  src/components/pipelines-metrics/PipelinesAverageDuration.tsx
  src/components/pipelines-metrics/PipelinesMetricsPage.tsx
  src/components/pipelines-overview/PipelineRunsNumbersChart.tsx
  src/components/pipelines-overview/PipelineRunsStatusCard.tsx
  src/components/pipelines-overview/PipelinesOverviewPage.tsx
  src/components/pipelines-overview/dateTime.ts
  src/components/pipelines-overview/list-pages/PipelineRunsListPage.tsx
  src/components/pipelines-overview/utils.ts
Labels: approved, lgtm, jira/valid-reference

#46 ODC-7468: Add URL params for all filters available on the Pipeline Overview page
  src/components/pipelines-metrics/PipelinesMetricsPage.tsx
  src/components/pipelines-overview/PipelinesOverviewPage.tsx
  src/components/pipelines-overview/RefreshIntervalDropdown.tsx
  src/components/pipelines-overview/SearchInput.tsx
  src/components/pipelines-overview/__tests__/PipelinesOverview.spec.tsx
  src/components/pipelines-overview/list-pages/PipelineRunsListPage.tsx
  src/components/pipelines-overview/utils.ts
Labels: approved, lgtm, jira/valid-reference

#56 OCPBUGS-28721: Enable metrics tab flag if TektonResults CR is present
  src/components/hooks/flagHookProvider.ts
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug
