Repository openshift-pipelines/console-plugin, pull requests merged in 2024-11, with the labels that each got.

#175 NO-JIRA: Update owners file after I changed my GitHub username
  OWNERS
Labels: approved, lgtm, jira/valid-reference

#171 Add dockerfile for console plugin
  .konflux/dockerfiles/.placeholder
  .konflux/dockerfiles/console-plugin.Dockerfile
  .konflux/patches/.placeholder
  openshift/README.md
Labels: approved, lgtm

#174 SRVKP-6463: Use Tasks from the `openshift-pipelines` namespace instead of ClusterTask
  console-extensions.json
  integration-tests/cypress/features/pipelines/create-from-builder-page.feature
  integration-tests/cypress/testData/customNodeDeployment.yaml
  integration-tests/cypress/testData/customPythonDeploymentConfig.yaml
  integration-tests/cypress/testData/petclinic-pipeline-all.yaml
  integration-tests/cypress/testData/pipelineWithParameterTypeArray.yaml
  integration-tests/cypress/testData/pipelines-workspaces/pipeline-task-tkn.yaml
  integration-tests/cypress/testData/pipelines-workspaces/pipeline-with-workspace.yaml
  integration-tests/cypress/testData/pipelines-workspaces/s2i-build-and-deploy-pipeline-using-workspace.yaml
  locales/en/plugin__pipelines-console-plugin.json
  src/components/auto-complete/__tests__/autoCompleteUtils.spec.ts
  src/components/auto-complete/autoCompleteUtils.ts
  src/components/catalog/providers/useTasksProvider.tsx
  src/components/pipeline-builder/PipelineBuilderForm.tsx
  src/components/pipeline-builder/PipelineBuilderPage.tsx
  src/components/pipeline-builder/PipelineBuilderVisualization.tsx
  src/components/pipeline-builder/__tests__/utils.spec.ts
  src/components/pipeline-builder/__tests__/validation-utils-data.ts
  src/components/pipeline-builder/__tests__/validation-utils.spec.ts
  src/components/pipeline-builder/hooks.ts
  src/components/pipeline-builder/types.ts
  src/components/pipeline-builder/update-utils.ts
  src/components/pipeline-builder/utils.ts
  src/components/pipeline-builder/validation-utils.ts
  src/components/pipeline-topology/BuilderFinallyNode.tsx
  src/components/pipeline-topology/PipelineTaskNode.tsx
  src/components/pipeline-topology/TaskListNode.tsx
  src/components/pipeline-topology/types.ts
  src/components/pipeline-topology/utils.ts
  src/components/pipelines-details/pipeline-visualization-utils.ts
  src/components/pipelines-details/types.ts
  src/components/pipelines-details/utils.ts
  src/components/pipelines-tasks/ClusterTaskList.tsx
  src/components/pipelines-tasks/ClusterTaskListPage.tsx
  src/components/pipelines-tasks/ClusterTaskRow.tsx
  src/components/pipelines-tasks/TaskRunsRow.tsx
  src/components/pipelines-tasks/TasksNavigationPage.tsx
  src/components/pipelines-tasks/index.ts
  src/components/task-quicksearch/__tests__/PipelineQuickSearchVersionDropdown.spec.tsx
  src/components/task-quicksearch/__tests__/PipelineQuicksearchDetails.spec.tsx
  src/components/task-quicksearch/__tests__/catalog-item-data.ts
  src/components/task-quicksearch/__tests__/pipeline-quicksearch-utils.spec.ts
  src/components/task-quicksearch/pipeline-quicksearch-utils.ts
  src/components/triggers-details/DynamicResourceLinkList.tsx
  src/components/utils/__tests__/pipeline-augment.spec.ts
  src/components/utils/pipeline-augment.ts
  src/components/utils/pipeline-utils.ts
  src/models.ts
  src/test-data/pipeline-data.ts
  src/types/pipeline.ts
Labels: approved, lgtm, jira/valid-reference

#182 SRVKP-6733: ReRun of Resolver based PipelineRuns fails from UI
  src/components/pipelineRuns-details/PipelineRunDetailsPage.tsx
  src/components/pipelineRuns-list/PipelineRunsKebab.tsx
  src/components/utils/utils.ts
  src/types/pipelineRun.ts
Labels: approved, lgtm, jira/valid-reference

#185 SRVKP-6741: Remove duplicate root attribute in nginx.conf
  nginx.conf
Labels: approved, lgtm, jira/valid-reference, ok-to-test

#192 Update base image from ubi8 to ubi9
  .konflux/dockerfiles/console-plugin.Dockerfile
Labels: approved, lgtm, jira/valid-reference

#193 SRVKP-6845: Remove userSettings dependencies
  src/components/pipeline-builder/SyncedEditorField.tsx
  src/components/pipeline-builder/const.ts
  src/components/pipeline-builder/synced-editor/__tests__/useEditorType.spec.ts
  src/components/pipeline-builder/synced-editor/index.tsx
  src/components/pipeline-builder/synced-editor/useEditorType.ts
  src/components/pipeline-builder/utils.ts
Labels: approved, lgtm, jira/valid-reference
