Repository openshift-pipelines/console-plugin, pull requests merged in 2024-05, with the labels that each got.

#97 ODC-7558: Add all Projects list page
  locales/en/plugin__pipelines-console-plugin.json
  src/components/list-pages/PipelinesTabbedPage.tsx
  src/components/pipelines-list/PipelinesTabbedPage.tsx
  src/components/projects-list/AllProjectsPage.scss
  src/components/projects-list/AllProjectsPage.tsx
  src/components/projects-list/ProjectsList.tsx
  src/components/projects-list/ProjectsRow.tsx
  src/components/projects-list/useProjectsColumns.tsx
  src/models.ts
Labels: approved, lgtm, jira/valid-reference

#98 OCPBUGS-33232: Fix Tasks lists from another namespace
  src/components/pipelines-tasks/TasksList.tsx
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#99 OCPBUGS-33238: Show same task name on terminal header and in task navigation
  src/components/logs/LogsWrapperComponent.tsx
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#100 OCPBUGS-33257: Fix loader for start pipeline and add trigger modal
  src/components/modals/LoadingModal.tsx
  src/components/pipelines-list/PipelineKebab.tsx
  src/components/start-pipeline/AddTriggerModal.tsx
  src/components/start-pipeline/StartPipelineModal.tsx
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#102 [console-plugin] OCPBUGS-33333: In PipelineList page PipelineRuns not fetched from tekton results
  src/components/pipelines-list/PipelinesList.tsx
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#104 OCPBUGS-33344: Fix details page Actions in dark mode
  src/components/details-page/DetailsPage.scss
  src/components/details-page/DetailsPage.tsx
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#106 OCPBUGS-33390: Add checks for OPENSHIFT_PIPELINE flag on Pipelines nav
  console-extensions.json
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#107 OCPBUGS-33518: Fix Pipeline details page with when expression using CEL expression
  src/components/pipelines-details/pipeline-visualization-utils.ts
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#105 OCPBUGS-33569: Remove duplicates code and cleanup
  console-extensions.json
  locales/en/plugin__pipelines-console-plugin.json
  src/components/common/dropdown.jsx
  src/components/pipeline-topology/CustomTaskNode.tsx
  src/components/pipeline-topology/PipelineTaskNode.tsx
  src/components/pipeline-topology/StatusIcons.tsx
  src/components/pipelineRuns-details/PipelineRunCustomDetails.tsx
  src/components/pipelineRuns-details/PipelineRunDetailsPage.tsx
  src/components/pipelineRuns-details/PipelineRunLogs.tsx
  src/components/pipelineRuns-details/RepositoryLinkList.tsx
  src/components/pipelineRuns-list/PipelineRunsList.tsx
  src/components/pipelineRuns-list/PipelineRunsListPage.tsx
  src/components/pipelineRuns-list/PipelineRunsRow.tsx
  src/components/pipelines-details/PipelineDetailsPage.tsx
  src/components/pipelines-details/PipelineVisualizationStepList.tsx
  src/components/pipelines-details/PipelineVisualizationTask.tsx
  src/components/pipelines-details/StatusIcon.tsx
  src/components/pipelines-list/PipelineKebab.tsx
  src/components/pipelines-list/PipelinesList.tsx
  src/components/pipelines-list/PipelinesTabbedPage.tsx
  src/components/pipelines-list/usePipelinesFilters.ts
  src/components/pipelines-tasks/TaskRunStatus.tsx
  src/components/pipelines-tasks/TaskRunsList.tsx
  src/components/pipelines-tasks/TaskRunsRow.tsx
  src/components/pipelines-tasks/tasks-details-pages/events/events.jsx
  src/components/repositories-list/RepositoriesList.tsx
  src/components/repositories-list/RepositoriesListPage.tsx
  src/components/repositories-list/useRepositoriesColumns.ts
  src/components/start-pipeline/StartPipelineForm.tsx
  src/components/start-pipeline/form-sections/PipelineWorkspacesSection.tsx
  src/components/text-column-field/TextColumnItemContent.tsx
  src/components/utils/link.tsx
  src/components/utils/pipeline-augment.ts
  src/components/utils/pipeline-utils.ts
  src/components/utils/pipelines-actions.tsx
  src/components/utils/pipelines-utils.ts
  src/components/utils/repository-utils.tsx
  src/components/utils/resource-link.tsx
  src/components/utils/utils.ts
  src/models.ts
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#110 OCPBUGS-33648: Fix Pipeline parameter form and Secret form
  src/components/common/SecretForm.tsx
  src/components/pipelines-details/PipelineForm.tsx
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#114 OCPBUGS-34180: [CONSOLE-PLUGIN] Update the Current Status Column text and fix the alignment issue observed in Firefox
  src/components/approval-tasks/ApprovalRow.scss
  src/components/utils/__tests__/pipeline-approval-utils.spec.ts
  src/components/utils/pipeline-approval-utils.ts
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug, jira/severity-critical

#115 [console-plugin] OCPBUGS-34479: Internet call happens in loop in PipelineRun list page
  src/components/hooks/useTaskRuns.ts
  src/components/hooks/useTektonResult.ts
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#112 OCPBUGS-34574: TaskRuns should not be fetched for Failed PLR's
  src/components/pipelineRuns-list/PipelineRunsRow.tsx
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug
