Repository openshift-pipelines/console-plugin, pull requests merged in 2025-02, with the labels that each got.

#232 SRVKP-7063: UI- results not displayed when pipeline run fails
  src/components/outputs/OutputTab.tsx
  src/components/outputs/ResultsList.tsx
Labels: approved, lgtm, jira/valid-reference

#247 [bot:main] update konflux configuration
  .tekton/console-plugin-1-18-console-plugin-pull-request.yaml
  .tekton/console-plugin-1-18-console-plugin-push.yaml
Labels: automated, hack

#248 [bot:release-v1.17.x] update konflux configuration
  .tekton/console-plugin-next-console-plugin-pull-request.yaml
  .tekton/console-plugin-next-console-plugin-push.yaml
Labels: automated, hack

#241 SRVKP-7095,SRVKP-7097,SRVKP-7098: Added missing translations
  locales/en/plugin__pipelines-console-plugin.json
  locales/es/plugin__pipelines-console-plugin.json
  locales/fr/plugin__pipelines-console-plugin.json
  locales/ja/plugin__pipelines-console-plugin.json
  locales/ko/plugin__pipelines-console-plugin.json
  locales/zh/plugin__pipelines-console-plugin.json
  src/components/details-page/DetailsPage.tsx
  src/components/pipeline-topology/PipelineVisualizationSurface.tsx
  src/components/pipelineRuns-details/PipelineRunDetailsPage.tsx
  src/components/pipelines-tasks/tasks-details-pages/TaskRunDetailsPage.tsx
  src/components/utils/horizontal-nav.tsx
Labels: approved, lgtm, jira/valid-reference

#262 [bot:main] update konflux configuration
  .konflux/1.18/application.yaml
  .konflux/1.18/component-console-plugin.yaml
  .konflux/1.18/image-console-plugin.yaml
  .konflux/1.18/tests.yaml
  .konflux/next/application.yaml
  .konflux/next/component-console-plugin.yaml
  .konflux/next/image-console-plugin.yaml
  .konflux/next/release-plan.yaml
  .konflux/next/tests.yaml
  .tekton/console-plugin-1-18-console-plugin-pull-request.yaml
  .tekton/console-plugin-1-18-console-plugin-push.yaml
  .tekton/prow.yaml
Labels: approved, lgtm, automated, hack

#280 SRVKP-7096: Pipelines - Pipelines - Start : Some content is in English
  locales/en/plugin__pipelines-console-plugin.json
  locales/es/plugin__pipelines-console-plugin.json
  locales/fr/plugin__pipelines-console-plugin.json
  locales/ja/plugin__pipelines-console-plugin.json
  locales/ko/plugin__pipelines-console-plugin.json
  locales/zh/plugin__pipelines-console-plugin.json
  src/components/start-pipeline/form-sections/PipelineTimeoutSection.tsx
Labels: approved, lgtm, jira/valid-reference

#264 [bot:main] update konflux configuration
  .konflux/main/image-console-plugin.yaml
  .tekton/boussole.yaml
  .tekton/console-plugin-main-console-plugin-pull-request.yaml
  .tekton/console-plugin-main-console-plugin-push.yaml
Labels: automated, hack
