Repository openshift-pipelines/console-plugin, pull requests merged in 2025-03, with the labels that each got.

#309 NO-JIRA: Update install result script
  scripts/install-results.sh
Labels: approved, lgtm, jira/valid-reference

#305 OCPBUGS-51120: Detect ipv4/ipv6 socket in pod ip for nginx conf
  charts/openshift-console-plugin/templates/configmap.yaml
  charts/openshift-console-plugin/templates/deployment.yaml
Labels: jira/valid-reference, jira/valid-bug, ok-to-test

#318 [bot:release-v1.17.x] update konflux configuration
  .konflux/1.18/application.yaml
  .konflux/1.18/component-console-plugin.yaml
  .konflux/1.18/image-console-plugin.yaml
  .konflux/1.18/tests.yaml
  .konflux/next/application.yaml
  .konflux/next/component-console-plugin.yaml
  .konflux/next/image-console-plugin.yaml
  .konflux/next/release-plan.yaml
  .konflux/next/tests.yaml
  .tekton/console-plugin-1-17-console-plugin-pull-request.yaml
  .tekton/console-plugin-1-17-console-plugin-push.yaml
  .tekton/console-plugin-1-18-console-plugin-pull-request.yaml
  .tekton/console-plugin-1-18-console-plugin-push.yaml
Labels: automated, hack

#321 [bot:release-v1.17.x] update konflux configuration
  .tekton/console-plugin-1-17-console-plugin-pull-request.yaml
  .tekton/console-plugin-1-17-console-plugin-push.yaml
Labels: automated, hack

#330 [bot:release-v1.15.x] update konflux configuration
  .tekton/console-plugin-1-15-console-plugin-pull-request.yaml
  .tekton/console-plugin-1-15-console-plugin-push.yaml
Labels: automated, hack
